version: "2.2.3"

services:
  productpage:
    container_name: 43-productpage
    build: ./docker/productpage
    image: 43/productpage
    ports:
      - "80:80"
    links:
      - details
      - reviews
  details:
    container_name: 43-details
    build:
      context: ./docker/details
      args:
        service_version: v1
        enable_external_book_service: true
    image: 43/details:v1
    expose:
      - "9080"
  ratings:
    container_name: 43-ratings
    build:
      context: ./docker/ratings
      args:
          service_version: v1
    image: 43/ratings:v1
    expose:
      - "9080"
  reviews:
    container_name: 43-reviews
    build:
      context: ./docker/reviews/reviews-wlpcfg
      args:
        service_version: v3
        enable_ratings: true
        star_color: red
    image: 43/reviews:v3
    environment:
      - SERVICE_VERSION=v3
      - ENABLE_RATINGS=true
      - STAR_COLOR=red
    links:
      - ratings
  reviews-v2:
    container_name: 43-reviews-v2
    build:
      context: ./docker/reviews/reviews-wlpcfg
      args:
        service_version: v2
        enable_ratings: true
        star_color: black
    image: 43/reviews:v2
    environment:
      - SERVICE_VERSION=v2
      - ENABLE_RATINGS=true
      - STAR_COLOR=black
    links:
      - ratings
  reviews-v1:
    container_name: 43-reviews-v1
    build:
      context: ./docker/reviews/reviews-wlpcfg
      args:
        service_version: v1
    image: 43/reviews:v1
    environment:
      - SERVICE_VERSION=v1
