version: "2.2.3"

services:
  productpage:
    container_name: 43-productpage
    build: ./productpage
    image: 43/productpage
    ports:
      - "80:80"
    links:
      - details
      - reviews
  details:
    container_name: 43-details
    build:
      context: ./details
      args:
        service_version: v1
        enable_external_book_service: true
    image: 43/details:v1
    expose:
      - "9080"
  reviews:
    container_name: 43-reviews
    build:
      context: ./reviews/reviews-wlpcfg
      args:
        service_version: v3
        enable_ratings: true
        star_color: red
    image: 43/reviews:v3
    environment:
      - SERVICE_VERSION=v3
      - ENABLE_RATINGS=true
      - STAR_COLOR=red
    links:
      - ratings
  ratings:
    container_name: 43-ratings
    build:
      context: ./ratings
      args:
          service_version: v1
    image: 43/ratings:v1
    expose:
      - "9080"
