version: "2.2.3"

services:
  productpage:
    container_name: 43-productpage
    build: ./productpage
    image: 43/productpage
    ports:
      - "80:80"
    links:
      - details
  details:
    container_name: 43-details
    build: ./details
    image: 43/details
    expose:
      - "9080"
